name: renda_machine_web
description: Renda Machine Web & Android version
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/background_space.png

  fonts:
    - family: Marlboro
      fonts:
        - asset: assets/fonts/Marlboro.ttf
